# Generated by Django 5.0.1 on 2024-01-18 15:28

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userdata',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_permissions',
        ),
    ]
